language: cpp
compiler:
  - gcc
  - clang

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-5
      - clang-3.6
      - libboost-all-dev

before_install:
  - if [[ "$CXX" == "clang++" ]]; then
      export CXX=clang++-3.6; export CC=clang-3.6;
    fi
  - if [[ "$CXX" == "g++" ]]; then
      export CXX=g++-5; export CC=gcc-5;
    fi

script:
  - cmake . && make -j2
  - make jank_test

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#jank"
    on_success: always
    on_failure: always
    use_notice: true
