language: nix

sudo: false

os:
  - linux

cache:
  - apt
  - vcpkg_installed

script:
  - export VCPKG_DISABLE_METRICS=1 && ./bin/install-vcpkg && ./vcpkg/vcpkg install
  - nix-shell --command "./bin/ci/travis"

after_success:
- lein with-profile coverage cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
