language: c++

sudo: false

os:
  - linux

compiler:
  - clang

cache:
  - apt: true
  - directories:
    - ${HOME}/.cache/vcpkg/archives
    - vcpkg_installed

install:
  - |
    export VCPKG_DISABLE_METRICS=1
    git clone https://github.com/Microsoft/vcpkg.git
    ./vcpkg/bootstrap-vcpkg.sh
    ./vcpkg/vcpkg install || true
    tail /home/travis/build/jank-lang/jank/vcpkg/buildtrees/folly/install-x64-linux-dbg-out.log

script:
  - ./bin/ci/travis

after_success:
- lein with-profile coverage cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
