language: c++

sudo: false

os:
  - linux
dist: jammy

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main'
      - sourceline: 'deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main'
    packages:
      - clang-14

compiler:
  - clang-14

cache:
  - apt: true
  - directories:
    - ${HOME}/.cache/vcpkg
    - vcpkg_installed

install:
  - export CC=clang-14 && export CXX=clang++-14
  - which clang-14 && clang-14 --version
  - |
    export VCPKG_DISABLE_METRICS=1
    git clone https://github.com/Microsoft/vcpkg.git
    ./vcpkg/bootstrap-vcpkg.sh
    ./vcpkg/vcpkg install || true
    cat /home/travis/build/jank-lang/jank/vcpkg/buildtrees/folly/config-x64-linux-out.log || true
    cat /home/travis/build/jank-lang/jank/vcpkg/buildtrees/folly/install-x64-linux-dbg-out.log || true

script:
  - ./bin/ci/travis

after_success:
- lein with-profile coverage cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
