language: clojure

sudo: false

os:
  - linux
  - osx

cache:
  -apt

script:
  - ./travis.sh

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#jank"
    on_success: always
    on_failure: always
    use_notice: true
