# TODO: Port this to Github actions.
language: nix

sudo: false

os:
  - linux

cache:
  -apt

script:
  - nix-shell --command "./travis.sh"

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#jank"
    on_success: always
    on_failure: always
    use_notice: true
