language: nix

sudo: false

os:
  - linux

cache:
  - apt
  - vcpkg_installed

script:
  - ./bin/install-vcpkg
  - nix-shell --command "./bin/ci/travis"

after_success:
- lein with-profile coverage cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
