version: ~> 1.0
import: nix-community/nix-travis-ci:nix.yml@main

sudo: false

os:
  - linux
dist: jammy

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main'
      - sourceline: 'deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main'
    packages:
      - clang-14

cache:
  - apt: true
  - directories:
    - ${HOME}/.cache/vcpkg

install:
  - export CC=clang-14 && export CXX=clang++-14
  - |
    export VCPKG_DISABLE_METRICS=1
    git clone https://github.com/Microsoft/vcpkg.git
    ./vcpkg/bootstrap-vcpkg.sh
    ./vcpkg/vcpkg install
    export VCPKG_ROOT="${PWD}/vcpkg"

script:
  - nix-shell --command "./bin/ci/test"
