language: nix

sudo: false

os:
  - linux

cache:
  - apt
  - ${HOME}/vcpkg/installed
  - vcpkg_installed

before_install:
  - sudo apt-get -y install clang
  - export CC=clang
  - export CXX=clang++

install:
  - |
    export VCPKG_DISABLE_METRICS=1
    git clone https://github.com/Microsoft/vcpkg.git
    ./vcpkg/bootstrap-vcpkg.sh
    ./vcpkg/vcpkg install

script:
  - nix-shell --command "./bin/ci/travis"

after_success:
- lein with-profile coverage cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
