# TODO: Port this to Github actions.
language: nix

sudo: false

os:
  - linux

cache:
  -apt

script:
  - nix-shell --command "./bin/ci/travis"

after_success:
- lein with-profile coverage cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.libera.chat#jank"
    on_success: always
    on_failure: always
    use_notice: true
