name: "Build"

on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # TODO: sanitize: [On, Off]
        os: [ubuntu-22.04, macos-12]
        build_type: [Debug, Release]
        include:
          - os: macos-12
            cc: clang
            cxx: clang++
          - os: ubuntu-22.04
            cc: clang-14
            cxx: clang++-14
          - os: ubuntu-22.04
            build_type: Debug
            codecov: on
            analysis: on
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      CODECOV: ${{ matrix.codecov }}
      ANALYSIS: ${{ matrix.analysis }}
    timeout-minutes: 180 # 3h
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - if: runner.os == 'Linux'
        name: Install apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl git zip build-essential libssl-dev libdouble-conversion-dev pkg-config ninja-build python3-pip cmake debhelper devscripts gnupg zlib1g-dev
          # Update this whenever the package list changes.
          version: 2022.11.19--13.06.50
      - if: runner.os == 'macOS'
        name: Install brew packages
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install curl git zip openssl double-conversion pkg-config ninja python cmake gnupg zlib
      - name: Cache vcpkg packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/vcpkg
            ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('vcpkg.json') }}
      - name: Cache Cling
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build/cling-build
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bin/build-cling') }}
      - name: Compile and test
        run: ${{ github.workspace }}/bin/ci/test -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
