name: "Lint"

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Install apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: shellcheck
          # Update this whenever the package list changes.
          version: 2022.10.16--22.13.50
      - name: Lint bash scripts
        run: find bin -type f -exec shellcheck -o all {} \;
