name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Provision
      run: source ${{ github.workspace }}/bin/ci/provision
    - name: Cache C++ packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/vcpkg
    - name: Compile and test
      run: nix-shell --command "${{ github.workspace }}/bin/ci/test"
