# TODO: Rename to build
name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: curl git zip build-essential libssl-dev libdouble-conversion-dev pkg-config ninja-build python3-pip cmake debhelper devscripts gnupg zlib1g-dev clang-14 llvm-14
        # Update this whenever the list changes.
        version: 2022/09/24--17.18.35
    # TODO: Cache Cling separately; hash on bin/build-cling
    - name: Cache C++ packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
          ${{ github.workspace }}/build/cling-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('vcpkg.json') }}
    - name: Provision
      run: |
        # These cause issues when building folly.
        sudo apt-get remove -y libsodium-dev liburing-dev
        export CC=clang-14
        export CXX=clang++-14
    - name: Compile and test
      run: "${{ github.workspace }}/bin/ci/test"
