name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Cache C++ packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/vcpkg
          ${{ github.workspace }}/build/cling-build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('vcpkg.json') }}
    - name: Provision
      run: source ${{ github.workspace }}/bin/ci/provision
    - name: Compile and test
      run: "${{ github.workspace }}/bin/ci/test"
